server:
  port: 80

eureka:
  client:
    register-with-eureka: false #服务消费者可以不向服务注册中心注册服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true  #服务消费者客户端需要去检索服务


######################### Ribbon 客户端超时控制 ###################################
ribbon:
  ReadTimeout: 6000 #建立连接所用的时间，适用于网络状况正常的情况下，两端两端连接所用的时间
  ConnectionTimeout: 6000 #建立连接后，服务器读取到可用资源的时间

######################配置请求超时时间##########################
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
####################配置具体方法超时时间 为 3 秒########################
    # hystrix:command:xxx#yyy(zzz):execution:isolation:thread:timeoutInMilliseconds=mmm:
    # xxx：为包含该服务方法的类的名称（通常为服务绑定接口的名称），例如 DeptHystrixService 接口。
          #yyy：服务方法名，例如 deptInfo_Timeout() 方法。
          #zzz：方法内的参数类型，例如 Integer、String 等等
          #mmm：要设置的超时时间，单位为毫秒（1 秒 =1000 毫秒）
    DeptHystrixService#deptInfo_Timeout(Integer):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
feign:
  hystrix:
    enabled: true #开启客户端 hystrix

logging:
  level:
    #feign 日志以什么样的级别监控该接口
    com.huge.feign.service.DeptFeignService: debug